$('#datepicker, #datepicker2').datetimepicker({
	controlType: 'select',
	oneLine: true,
	timeFormat: 'HH:mm:ss',
	timeOnlyTitle: 'Escolha o horário',
	timeText: 'Horário',
	hourText: 'Hora',
	minuteText: 'Minutos',
	secondText: 'Segundos',
	millisecText: 'Milissegundos',
	microsecText: 'Microssegundos',
	timezoneText: 'Fuso horário',
	currentText: 'Agora',
	closeText: 'Fechar',
	timeFormat: 'HH:mm:ss',
	timeSuffix: '',
	amNames: ['a.m.', 'AM', 'A'],
	pmNames: ['p.m.', 'PM', 'P'],
	isRTL: false,
	changeMonth: true,
	changeYear: true,
	dayNames: ["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"],
	dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
	dayNamesShort: [ "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab" ],
	monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
	nextText: 'Próximo',
	prevText: 'Anterior',
	dateFormat: "dd/mm/yy",
});